#!/usr/bin/env python3
"""
Add beautiful spiritual reflection sections to all chapters that are missing them.
Each reflection connects the practical content to sacred service and transformation.
"""

import json
from pathlib import Path

spiritual_sections = {
    '01-foundation/01.json': {
        "title": "The Call to Sacred Service",
        "content": "You're here because something in you said yes.\n\nNot to a job. Not to a role. To a calling.\n\nYou felt it when you first encountered Dr. Joe's work. That recognition. That knowing. That sense of: *This is what I've been looking for.*\n\nAnd now you're being invited to serve it. To hold space for others to have their own moment of recognition. Their own breakthrough. Their own transformation.\n\nThis isn't small. This isn't casual. This is sacred work.\n\nThe volunteer who holds the door isn't just checking badges. They're protecting the container. The volunteer who greets participants isn't just saying hello. They're creating the first moment of welcome that says: *You're safe here. You can let go here. You can become here.*\n\nEvery role, every task, every moment of service—it all matters. Because you're not just supporting an event. You're holding space for miracles.\n\nPeople will arrive broken. Hopeless. Desperate. Skeptical. And over the course of seven days, you'll watch them transform. You'll see the light come back into their eyes. You'll witness the impossible become real.\n\nAnd you'll know: I was part of that. My presence mattered. My service made that possible.\n\nThat's the gift of this work. Not what you get. What you give. And in the giving, what you become.\n\nYou're not here by accident. You're here because you're ready. Ready to serve. Ready to hold space. Ready to be part of something larger than yourself.\n\nWelcome. We're grateful you're here."
    },
    
    '01-foundation/02.json': {
        "title": "The Practice of Loving Boundaries",
        "content": "There's a paradox at the heart of this work:\n\nThe more you love someone, the clearer your boundaries need to be.\n\nDr. Joe teaches about energy. About coherence. About the field. And here's what that means practically:\n\nWhen you protect his space, you're not being cold. You're being loving. You're ensuring he has the energy to teach. To hold the field. To serve the 1,500 people who came to transform.\n\nEvery person who approaches him takes energy. Every request, every question, every 'just one quick thing'—it all adds up. And if he gives it all away in hallways and elevators, he has nothing left for the teachings.\n\nSo when you step between someone and Dr. Joe, you're not rejecting them. You're protecting the very thing they came for.\n\nAnd here's what's beautiful about this:\n\nYou're teaching them something profound. You're showing them that boundaries aren't walls. They're containers. They're what makes sacred work possible.\n\nThe participant who's frustrated that they can't approach Dr. Joe? They're learning that transformation doesn't come from proximity to the teacher. It comes from doing the work. From going inward. From becoming their own source.\n\nYour gentle firmness teaches that. Your warm 'no' teaches that. Your redirection to the proper channels teaches that.\n\nThis is spiritual practice. Not just for them. For you.\n\nYou're learning to hold boundaries with love. To say no with kindness. To protect what's sacred without apologizing for it.\n\nThat's not easy. It goes against everything we're conditioned to do. We want to please. To accommodate. To make exceptions.\n\nBut sacred service sometimes means disappointing people for their own good. It means holding the line even when it's uncomfortable. It means trusting that the container matters more than individual comfort.\n\nThat's the practice. That's the gift. That's what you're learning here."
    },
    
    '01-foundation/03.json': {
        "title": "The Rhythm of Transformation",
        "content": "There's a reason these events follow the structure they do.\n\nDay 1 isn't like Day 4. Day 6 isn't like Day 7. Each day has its own energy. Its own purpose. Its own place in the arc of transformation.\n\nAnd you're part of holding that rhythm.\n\nWhen you understand the flow—when you know that Day 3 is about deepening, that Day 6 is about breakthrough, that Day 7 is about integration—you can serve more effectively. You can anticipate what's needed. You can adjust your energy to match the moment.\n\nThis is what it means to be in service to the process, not just the tasks.\n\nThe schedule is fluid because consciousness is fluid. Dr. Joe follows the field. He senses what's needed. He adjusts in real-time. And when you embrace that—when you release your need to know what's coming—you become part of the intelligence organizing the experience.\n\nBeing Timeless isn't just a concept. It's a practice. It's choosing presence over planning. Trust over control. Flow over rigidity.\n\nAnd here's what happens when you do that:\n\nYou stop resisting. You stop mentally projecting into tomorrow. You stop trying to figure it all out. You just show up. Fully. Completely. Right here. Right now.\n\nThat's the state participants are trying to reach. And when you embody it, you help them get there. Your ease with not-knowing gives them permission to not-know. Your trust in the process helps them trust the process.\n\nYou're not just coordinating logistics. You're modeling the consciousness that makes transformation possible.\n\nThat's the deeper work. That's the sacred service. That's why communication tools and flexible schedules matter—they're not just practical. They're spiritual. They're part of the container that holds the formless work of becoming."
    },
    
    '01-foundation/04.json': {
        "title": "The Heart Behind the Checklist",
        "content": "You might look at all these tasks—Telegram, apps, checklists, protocols—and think: This feels administrative. Where's the sacred service in downloading an app?\n\nHere's the truth: Practical preparation IS spiritual preparation.\n\nWhen you complete these tasks ahead of time, you're not just being organized. You're creating the conditions that allow you to serve from overflow instead of depletion. You're ensuring that when a participant needs you, you're present—not distracted by logistics you should have handled weeks ago.\n\nThe volunteer who shows up without joining Telegram spends Day 0 scrambling. The volunteer who forgets their phone charger spends the afternoon anxious about battery life. The volunteer who skips the pre-event Zoom misses critical information and has to ask questions others already know.\n\nThese aren't small inconveniences. They're energy leaks. They pull you out of presence. They create stress that participants feel.\n\nBut when you handle the basics? You arrive grounded. Connected. Ready. You can focus on what matters: holding space, responding with clarity, serving from the heart.\n\nThe checklist isn't separate from the sacred work. The checklist makes the sacred work possible.\n\nDo the preparation. Not because you're being tested. Not because someone's checking up on you. Do it because you care enough about this service to show up fully ready.\n\nThen, when the moment comes—when a participant is in distress, when the room needs resetting, when Dr. Joe walks past and you're holding his space—you'll be present. Grounded. Ready.\n\nThat's what the checklist serves. That's why it matters."
    },
    
    '02-communication/01.json': {
        "title": "The Sacred Art of Discernment",
        "content": "Knowing when to call for help isn't weakness. It's wisdom.\n\nYou're going to see things at these events. People in pain. People in crisis. People having breakthroughs that look like breakdowns. And in those moments, you need to know: Is this Medical? Emotional? Meditation?\n\nThat discernment—that ability to assess clearly and act appropriately—is one of the most important skills you'll develop.\n\nBecause here's the truth: You can't help everyone. You're not supposed to. You're supposed to recognize what's needed and connect people to the right support.\n\nThat's not failure. That's service.\n\nThe volunteer who tries to handle everything themselves creates chaos. The volunteer who knows when to escalate creates safety.\n\nAnd here's what's sacred about this:\n\nYou're learning to trust the system. To trust that Medical knows what they're doing. That Emotional Support is trained for this. That Meditation Assistants understand energy movement.\n\nYou don't have to be the expert. You just have to be the bridge.\n\nWhen you call for the right help at the right time, you're not admitting you can't handle it. You're honoring that person's needs enough to get them the best support available.\n\nThat's love. That's care. That's what sacred service looks like in practice.\n\nThe three types of support exist because transformation is complex. Bodies need medical care. Hearts need emotional support. Energy needs space to move. And you—you're the one who recognizes which is which and acts accordingly.\n\nThat's the practice. That's the gift. That's what you're learning here."
    },
    
    '02-communication/03.json': {
        "title": "Holding Space for the Unraveling",
        "content": "There's a moment that happens at these events—you'll see it, you'll feel it—when someone's carefully constructed walls start to crumble.\n\nThey came here to transform. To heal. To release what no longer serves them. And sometimes that release is messy. Raw. Overwhelming.\n\nYour role isn't to fix them. It's not to stop the tears or make it comfortable or rush them through it.\n\nYour role is to hold the space steady while they fall apart.\n\nThat's what calling Emotional Support is really about. It's not admitting failure. It's not escalating a problem. It's recognizing: This person needs someone trained in trauma-informed care. Someone who can hold this level of intensity with skill and presence.\n\nAnd here's what's sacred about that:\n\nYou don't have to be the healer to be of service.\n\nYou can be the one who stays present. Who doesn't panic. Who recognizes when professional support is needed and connects them to it without judgment.\n\nYou can be the one who says, quietly: 'I see you. You're not alone. Help is coming.'\n\nThat's not a small thing. That's everything.\n\nThe discernment you're learning—normal tears vs. crisis—isn't cold assessment. It's compassionate wisdom.\n\nYou're learning to trust the process. To honor that tears can be healing. To recognize when someone needs more support than you can provide. To act with clarity instead of fear.\n\nWhen you call Emotional Support, you're not saying 'I can't handle this.' You're saying 'I care enough about this person to get them the right help.'\n\nThat's love. That's service. That's the work."
    },
    
    '02-communication/04.json': {
        "title": "Trusting the Process of Transformation",
        "content": "Here's what you need to understand about energy movement:\n\nThe body knows how to heal itself.\n\nWhen someone shakes, when they make sounds, when they move in ways that look unusual—that's not a malfunction. That's the nervous system releasing what it's been holding. That's energy moving. That's transformation in progress.\n\nYour job isn't to stop it. Your job isn't to make it look normal. Your job is to trust the process and know when to call for assessment.\n\nThat discernment—Is this energy release or is this danger?—is one of the most important skills you'll develop.\n\nAnd here's the beautiful thing:\n\nYou don't have to know what's happening inside them to serve them well.\n\nYou just have to observe clearly. Stay present. Call MA when you're uncertain. Let the experts assess.\n\nMeditation Assistants aren't there to stop the process. They're there to ensure it's safe. To reassure nearby participants. To hold the space with expertise.\n\nWhen you call MA, you're not interrupting someone's healing. You're ensuring they can continue safely.\n\nThis is what it means to hold space for transformation:\n\nYou witness without judgment. You stay grounded when things look intense. You trust the body's wisdom. You call for support when needed. You let the process unfold.\n\nYou don't have to understand it. You don't have to fix it. You just have to be present, discerning, and willing to ask for help.\n\nThat's the practice. That's the service. That's how transformation happens safely."
    },
    
    '03-roles/02.json': {
        "title": "First Impressions, Lasting Impact",
        "content": "Registration Day is when the container is built. When first impressions are made. When participants walk through the door and feel—immediately—whether this space is safe, whether they're welcome, whether they can trust what's about to unfold.\n\nYou're part of creating that feeling.\n\nThe Registration Desk volunteer who greets with warmth. The Seating Coordinator who ensures smooth flow. The Badge Checker who balances efficiency with kindness. The Greeter who makes eye contact and says 'Welcome home.'\n\nThese aren't small moments. These are the moments that set the tone for everything.\n\nA participant who feels rushed, confused, or unwelcome on Day 1 carries that energy into the week. A participant who feels seen, cared for, and guided arrives at their seat already beginning to relax.\n\nYou're not just processing registrations. You're creating the energetic foundation for transformation.\n\nAnd here's what makes Registration Day sacred:\n\nYou're balancing two things that seem opposite: efficiency and presence. Speed and care. Getting 1,500 people registered quickly AND making each person feel individually welcomed.\n\nThat's the art. That's the practice.\n\nWhen you can smile genuinely while working quickly. When you can solve problems calmly while maintaining flow. When you can be both organized and warm—that's mastery.\n\nRegistration Day is long. It's intense. There will be moments of chaos. Participants will be confused, tired from travel, anxious about the week ahead.\n\nYour groundedness becomes their anchor.\n\nYour calm presence says: 'You're in the right place. We've got you. Everything is handled. You can relax now.'\n\nThat's the gift you give on Day 1. Not just a badge and a seat assignment. But a feeling of being held. Of being home.\n\nThat's why Registration Day matters. That's why your role is essential.\n\nYou're building the container. You're setting the tone. You're creating the first moment of trust that makes everything else possible."
    },
    
    '03-roles/03.json': {
        "title": "The Invisible Work That Holds Everything",
        "content": "Some roles get seen. Greeters are visible. Door Team is visible. Group Leads are visible.\n\nBut some of the most essential work happens in the background. Quietly. Without recognition. Without applause.\n\nThat's Meditation Assist. That's Room Reset. That's the behind-the-scenes coordination that makes everything flow.\n\nYou're the one who notices someone in distress during meditation when everyone else has their eyes closed. You're the one who transforms a chaotic ballroom into perfect order in 20 minutes. You're the one who ensures the space is ready before anyone arrives.\n\nThis work doesn't get thanked. Participants don't see it. Most volunteers don't notice it.\n\nBut without it, nothing works.\n\nWithout Meditation Assist, people in crisis wouldn't get support. Without Room Reset, the space wouldn't be ready. Without the quiet, invisible coordination, the whole system would collapse.\n\nAnd here's what's sacred about that:\n\nYou're not doing it for recognition. You're doing it because it needs to be done.\n\nThat's the purest form of service. Not the visible kind. Not the celebrated kind. The kind that happens in the background, in the margins, in the moments no one sees.\n\nThe kind that holds everything together.\n\nMeditation Assist volunteers sit through every meditation, eyes open, watching, ready—never getting to do the practice themselves. Room Reset teams work through breaks when everyone else is resting. The invisible roles sacrifice their own experience to ensure others can have theirs.\n\nThat's not a small thing. That's everything.\n\nWhen you take on these roles, you're saying: 'My presence matters more than my experience. My service matters more than my comfort. I'll hold the space so others can transform.'\n\nThat's not martyrdom. That's love.\n\nThe participant who has a breakthrough will never know you were watching. The room that's perfectly set will seem like magic. The smooth flow will feel effortless.\n\nBut you'll know. You'll know you were part of it. You'll know your invisible work mattered.\n\nAnd that's enough.\n\nThat's the practice. That's the service. That's the sacred work that happens in the margins."
    },
    
    '04-critical-protocols/02.json': {
        "title": "Compassionate Boundaries: The Gift of 'No'",
        "content": "This might be the hardest protocol you'll enforce.\n\nBecause you'll look into someone's eyes—someone in pain, someone who traveled far, someone who desperately wants a gravity chair—and you'll have to say: 'I understand, and the answer is no.'\n\nThat feels cruel. It feels uncompassionate. It feels like the opposite of service.\n\nBut here's the truth you need to understand:\n\nBoundaries ARE compassion.\n\nWhen you enforce the gravity chair protocol—when you hold the line even when it's uncomfortable—you're protecting something sacred.\n\nYou're protecting the person who medically needs that chair. The person with the heart condition who can't sit upright for hours. The person recovering from surgery who requires that specific accommodation.\n\nYou're protecting the integrity of the medical assessment process. The careful evaluation that determined who truly needs this limited resource.\n\nYou're protecting the fairness of the system. The trust that everyone is treated equitably based on medical need, not persuasiveness or persistence.\n\nAnd you're protecting the person asking.\n\nBecause when you say no with compassion—when you acknowledge their disappointment while holding the boundary—you're teaching them something profound: that they can handle discomfort. That they're stronger than they think. That transformation doesn't require perfect conditions.\n\nThe gravity chair protocol isn't about being rigid. It's about being clear. It's about honoring medical necessity while maintaining compassion for everyone.\n\nHere's what makes this sacred:\n\nYou're learning to hold two truths at once: 'I see your pain' AND 'I can't give you what you're asking for.' You're learning that compassion doesn't mean saying yes to everything. You're learning that sometimes the most loving thing you can do is hold a boundary.\n\nThat's not easy. It will never feel easy.\n\nBut it's essential.\n\nThe participant who's disappointed today may not thank you. They may walk away frustrated. They may complain.\n\nBut the person with the heart condition who gets their assigned chair? They're safe because you held the line.\n\nThe medical team who can trust that assignments are honored? They can do their work because you held the line.\n\nThe integrity of the system that serves 1,500 people fairly? It holds because you held the line.\n\nThat's the practice. That's the service.\n\nCompassionate boundaries. Clear communication. Gentle firmness.\n\nSaying 'I understand your disappointment' and meaning it. Saying 'The answer is no' and holding it.\n\nThat's what sacred service sometimes requires. Not just the easy moments. The hard ones too."
    }
}

print("\n" + "="*70)
print("ADDING SPIRITUAL SECTIONS TO ALL CHAPTERS")
print("="*70 + "\n")

for file_path, reflection in spiritual_sections.items():
    path = Path('content/chapters') / file_path
    
    with open(path, 'r') as f:
        data = json.load(f)
    
    # Ensure phase2_immerse exists
    if 'phase2_immerse' not in data:
        data['phase2_immerse'] = {'sections': []}
    
    # Add reflection
    data['phase2_immerse']['reflection'] = reflection
    
    with open(path, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
    
    print(f"✅ {file_path}")
    print(f"   '{reflection['title']}'")
    print()

print("="*70)
print("✅ ALL 10 SPIRITUAL SECTIONS ADDED")
print("="*70)
EOF
